import { DESIGN_SYSTEM_SCHEMA_VERSION, DESIGN_SYSTEM_THEME, designTokens } from "./tokens.js";
import { flattenTokens, tokenPathToCssVar, validateDesignTokens } from "./tokenSchema.js";

function cssValue(value) {
  if (typeof value !== "string" || !value.startsWith("$")) return String(value);
  return `var(${tokenPathToCssVar(value.slice(1))})`;
}

function declarationLines(entries) {
  return entries.map(({ path, value }) => `  ${tokenPathToCssVar(path)}: ${cssValue(value)};`).join("\n");
}

/** Generate the framework-agnostic token layer for app and offline publication consumers. */
export function generateTokenCss({ layer = "tokens" } = {}) {
  validateDesignTokens();
  const entries = flattenTokens(designTokens);
  return [
    `/* Generated by Trama design system. Schema ${DESIGN_SYSTEM_SCHEMA_VERSION}. */`,
    `/* Theme: ${DESIGN_SYSTEM_THEME}. */`,
    "@layer reset, legacy, tokens, primitives, patterns, routes, states, utilities;",
    `@layer ${layer} {`,
    "  :root,",
    `  :root[data-theme="${DESIGN_SYSTEM_THEME}"],`,
    `  [data-theme="${DESIGN_SYSTEM_THEME}"] {`,
    declarationLines(entries),
    "  }",
    "}",
    ""
  ].join("\n");
}
