// Generated by scripts/build-design-tokens.mjs. Do not edit by hand.
export const DESIGN_SYSTEM_MANIFEST = Object.freeze({
  "schemaVersion": "1.0.0",
  "theme": "matcha",
  "hash": "ba96f9e1921a1e533065dacb1f86b8273b3124042c44ac40efd43926aeb7dd90",
  "tokenCount": 237
});
