// Generated by scripts/build-design-tokens.mjs. Do not edit by hand.
export const DESIGN_SYSTEM_MANIFEST = Object.freeze({
  "schemaVersion": "1.0.0",
  "theme": "matcha",
  "hash": "52ec92400717f6fbf71b5ebc379cd32cfc0d0f71decf2bf38231ca862abf79a9",
  "tokenCount": 237
});
